### ISSUE TITLE
Issuu Api will be deprecated

### ISSUE THREAD

**Issue by davidsousa5** [issuu/issuu-panel#1]
Currently Issuu is deprecating the used [api](https://help.issuu.com/hc/en-us/articles/15492608401051-Deprecation-Notice-Issuu-Search-API) and migrating to a new [api](https://api.issuu.com/v2/reference). Could this be updated or could you contact Issuu to solve this?

**Comment by augustovicente** [comment]
Fixed by https://github.com/issuu/issuu-panel/pull/3
